services:
  # web:
    # container_name: web
    # build:
      # context: .
      # dockerfile: apps/web/dockerfile.dev.yaml
    # ports:
      # - "3000:3000"
    # env_file:
      # -  ./apps/web/.env
    # networks:
      # - caller
    # deploy:
      # resources:
        # limits:
          # cpus: '1.5'
          # memory: 2G     
  http-server:
    container_name: http-server
    build:
      context: .
      dockerfile: apps/http-server/dockerfile.dev.yaml 
    restart: unless-stopped
    env_file:
      - ./apps/http-server/.env
       
    ports:
      - "3002:3002"  
    deploy:
      resources:
        limits:
          cpus: '0.45'
          memory: 1G    
    networks:
      - caller
  mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_DATABASE=api
    volumes:
      - mongo_data:/data/db
    networks:
      - caller
    healthcheck:
      test:
        [
         "CMD",
         "mongosh",
         "mongodb://root:rootpassword@localhost:27017/admin",
         "--quiet",
         "--eval",
         "db.runCommand({ ping: 1 }).ok"
       ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
  signaling-server:
    container_name: signaling-server
    build:
      context: .
      dockerfile: apps/signaling-server/dockerfile.dev.yaml 
    restart: unless-stopped
    env_file:
      - ./apps/signaling-server/.env
       
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 1G    
    networks:
    - caller    
networks:
  caller:
    name: caller
    driver: bridge
volumes:
  mongo_data:    
